// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package infrastructure

import (
	"github.com/MSHR-Dec/go_backend/internal/interfaces/controller"
	"github.com/MSHR-Dec/go_backend/internal/interfaces/persistence"
	"github.com/MSHR-Dec/go_backend/internal/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initializeUser(db *gorm.DB) *controller.UserController {
	userRepository := persistence.NewUserRepository(db)
	userInteractor := usecase.NewUserInteractor(userRepository)
	userController := controller.NewUserController(userInteractor)
	return userController
}

func initializeTask(db *gorm.DB) *controller.TaskController {
	taskRepository := persistence.NewTaskRepository(db)
	taskInteractor := usecase.NewTaskInteractor(taskRepository)
	taskController := controller.NewTaskController(taskInteractor)
	return taskController
}
