// Code generated by MockGen. DO NOT EDIT.
// Source: ../../usecase/task.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	usecase "github.com/MSHR-Dec/go_backend/internal/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskUsecase is a mock of TaskUsecase interface.
type MockTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUsecaseMockRecorder
}

// MockTaskUsecaseMockRecorder is the mock recorder for MockTaskUsecase.
type MockTaskUsecaseMockRecorder struct {
	mock *MockTaskUsecase
}

// NewMockTaskUsecase creates a new mock instance.
func NewMockTaskUsecase(ctrl *gomock.Controller) *MockTaskUsecase {
	mock := &MockTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUsecase) EXPECT() *MockTaskUsecaseMockRecorder {
	return m.recorder
}

// ListByUserID mocks base method.
func (m *MockTaskUsecase) ListByUserID(input usecase.ListByUserIDInput) ([]usecase.ListByUserIDOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", input)
	ret0, _ := ret[0].([]usecase.ListByUserIDOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockTaskUsecaseMockRecorder) ListByUserID(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockTaskUsecase)(nil).ListByUserID), input)
}
